global:
  scrape_interval: 15s # How often to fetch data
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'raspberry_pi_stats'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
